version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=alejmendez.87@gmail.com
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh

  app:
    image: dunglas/frankenphp
    restart: always
    container_name: laratrufa_app
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=laratrufas
      - DB_USERNAME=laratrufas
      - DB_PASSWORD=laratrufas
      - VIRTUAL_HOST=app.agricolafrayleon.app
      - LETSENCRYPT_HOST=app.agricolafrayleon.app
      - LETSENCRYPT_EMAIL=alejmendez.87@gmail.com
      - VIRTUAL_PORT=443
    volumes:
      - .:/app
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - nginx-proxy
      - letsencrypt
      - db

  db:
    image: postgres:16.3-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: laratrufas
      POSTGRES_USER: laratrufas
      POSTGRES_PASSWORD: laratrufas
      PGDATA: /var/lib/postgresql/data/laratrufas/
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/laratrufas

volumes:
  certs:
  html:
  vhostd:
  acme:
  pgdata:
  caddy_data:
  caddy_config:
