version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
      - ./.docker/nginx/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=alejmendez.87@gmail.com
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh

  app:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    # restart: always
    container_name: laratrufa_app
    environment:
      - VIRTUAL_HOST=app.agricolafrayleon.app
      - LETSENCRYPT_HOST=app.agricolafrayleon.app
      - LETSENCRYPT_EMAIL=alejmendez.87@gmail.com
      - LETSENCRYPT_SINGLE_DOMAIN_CERTS=true
      - VIRTUAL_PORT=80
    volumes:
      - .:/var/www
      - ./.docker/nginx/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf
      - ./.docker/php/docker-php.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - nginx-proxy
      - letsencrypt
      - db

  db:
    image: postgres:16.3-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/laratrufas/
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  certs:
  html:
  vhostd:
  acme:
  pgdata:
