name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.2.1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          cd /home/ubuntu/laratrufas
          sudo systemctl stop nginx
          sudo systemctl stop php8.3-fpm
          sudo systemctl stop octane
          git pull origin main
          composer install --optimize-autoloader --no-dev
          composer dump-autoload
          php artisan migrate --force
          php artisan optimize
          sudo systemctl start octane
          sudo systemctl start php8.3-fpm
          sudo systemctl start nginx
